const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
(async()=>{
 fs.mkdirSync('docs/screenshots',{recursive:true});
 const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL || 'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');
 await page.getByRole('button',{name:'Разобрать задание →'}).waitFor();
 await page.screenshot({path:'docs/screenshots/01-start.png',fullPage:true});
 await page.getByLabel('Условие задания').fill('Подготовить учебный проект по анализу данных. Собрать данные, проверить пропуски, построить графики и написать выводы. Предоставить отчёт на 15 страниц и презентацию на 10 слайдов. Указать источники и описать ограничения выбранного метода.');
 await page.screenshot({path:'docs/screenshots/02-input.png',fullPage:true});
 await page.getByRole('button',{name:'Разобрать задание →'}).click();
 await page.getByRole('heading',{name:'Твой чек-лист'}).waitFor();
 await page.screenshot({path:'docs/screenshots/03-result.png',fullPage:true});
 await page.getByRole('checkbox').first().click();
 await page.getByText('1 из 5 шагов').waitFor();
 await page.screenshot({path:'docs/screenshots/04-checklist.png',fullPage:true});
 const date=new Date();date.setDate(date.getDate()+5);
 const end=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
 await page.getByLabel('Успеть к дедлайну').fill(end);
 await page.getByRole('button',{name:'Построить план по дням'}).click();
 await page.getByText('Изменение даты сохранит выполненные шаги.').waitFor();
 await page.waitForFunction(()=>document.querySelector('.today li'));
 await page.screenshot({path:'docs/screenshots/05-deadline.png',fullPage:true});
 await page.reload();
 await page.getByText('1 из 5 шагов').waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'docs/screenshots/06-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile overflow');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('Browser flow passed: input, analyze, checkbox, deadline, reload, mobile; no JS errors.');
 await browser.close();
})();
