import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const localDate = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const pretty = value => new Date(value+'T12:00:00').toLocaleDateString('ru', {day:'numeric',month:'long'});
async function api(path, method='GET', body) {
  const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 30000);
  try {
    const response = await fetch('/api'+path, {method, credentials:'same-origin', signal:controller.signal, headers:body instanceof FormData ? {} : {'Content-Type':'application/json'}, body:body ? (body instanceof FormData ? body : JSON.stringify(body)) : undefined});
    const data = await response.json();
    if (!response.ok) throw Object.assign(new Error(data.message || 'Не удалось выполнить запрос.'), {code:data.code});
    return data;
  } catch(e) { if (e.name==='AbortError') throw new Error('Разбор занял слишком много времени. Попробуйте ещё раз.'); if(e instanceof TypeError) throw new Error('Нет соединения с сервером. Проверьте подключение.'); throw e; }
  finally {clearTimeout(timer);}
}

function App() {
  const [text,setText]=useState(''), [file,setFile]=useState(null), [due,setDue]=useState(''), [plan,setPlan]=useState(null), [loading,setLoading]=useState(false), [error,setError]=useState(''), [expanded,setExpanded]=useState(true), [saving,setSaving]=useState(false), [pending,setPending]=useState(null), [demo,setDemo]=useState(false), [restoring,setRestoring]=useState(true);
  useEffect(()=> { api('/config').then(x=>setDemo(x.demo_mode)).catch(()=>{}); api('/plan').then(p=>{setPlan(p);setDue(p.deadline_date||'');setExpanded(false);}).catch(e=>{if(e.code!=='SESSION_NOT_FOUND')setError(e.message);}).finally(()=>setRestoring(false)); },[]);
  useEffect(()=>{const id=setInterval(()=>{if(plan && plan.today.date!==localDate()) api('/plan').then(setPlan).catch(()=>{});},60000);return()=>clearInterval(id);},[plan]);
  async function analyze(e) {e.preventDefault();setError('');setLoading(true);try {let body={text,deadline_date:due||null};if(file){body=new FormData();body.append('text',text);body.append('file',file);if(due)body.append('deadline_date',due);}const p=await api('/analyze','POST',body);setPlan(p);setExpanded(false);setText('');setFile(null);}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function toggle(step){setPending(step.id);setError('');try{const result=await api('/steps/'+step.id,'PATCH',{session_id:plan.session_id,done:!step.done});setPlan(p=>({...p,steps:p.steps.map(s=>s.id===result.id?{...s,done:result.done}:s),today:{...p.today,steps:p.today.steps.map(s=>s.id===result.id?{...s,done:result.done}:s)}}));}catch(e){setError(e.message);}finally{setPending(null);}}
  async function schedule(e){e.preventDefault();setSaving(true);setError('');try{setPlan(await api('/plan/deadline','POST',{session_id:plan.session_id,deadline_date:due}));}catch(e){setError(e.message);}finally{setSaving(false);}}
  const done=plan?.steps.filter(s=>s.done).length||0;
  return <main><header><a className="brand" href="/"> <span className="logo">✓</span> Deadline Buddy <span className="ai">AI</span></a><span className="header-note">Меньше тревоги. Больше ясности.</span></header>
    {demo && <aside className="demo">Демонстрационный режим · показан пример плана, ИИ не подключён</aside>}
    <section className="intro"><span className="eyebrow">ТВОЯ ТОЧКА СТАРТА</span><h1>{plan?'Большая задача. Маленькие шаги.':'Сложное задание —'}{!plan&&<><br/><em>понятный план.</em></>}</h1><p>{plan?'План готов. Начни с одного шага — остальное уже разложено по полочкам.':'Добавь условие. Buddy выделит главное, соберёт чек-лист и поможет успеть к дедлайну.'}</p></section>
    {restoring ? <p role="status">Восстанавливаем план…</p> : <>
    {plan&&<button className="text-button" onClick={()=>setExpanded(!expanded)} disabled={loading}>{expanded?'Скрыть форму':'＋ Разобрать новое задание'}</button>}
    {expanded&&<section className="card input-card"><div className="card-heading"><h2><span className="number">01</span> С чего начнём?</h2><span className="muted">Текст или PDF</span></div><form onSubmit={analyze}><fieldset disabled={loading}><label htmlFor="task">Условие задания</label><textarea id="task" value={text} onChange={e=>setText(e.target.value)} placeholder="Вставьте условие задания целиком: что нужно сделать, какие требования учесть и что сдать в результате…" rows={7}/><div className="input-meta"><span>От 200 до 20 000 символов</span><span>{text.length.toLocaleString('ru')} / 20 000</span></div><div className="form-bottom"><div><label className="upload" htmlFor="pdf">↥ {file ? file.name : 'Загрузить PDF'}<input id="pdf" type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files[0]||null)}/></label>{file&&<button type="button" className="text-button" onClick={()=>{setFile(null);document.getElementById('pdf').value='';}}>Убрать</button>}<small>До 5 МБ · с текстовым слоем</small></div><div><label htmlFor="initial-date">Дата сдачи <span className="muted">· необязательно</span></label><input id="initial-date" type="date" min={localDate()} value={due} onChange={e=>setDue(e.target.value)}/></div></div>{file&&text.trim()&&<small>Будет разобран введённый текст. PDF не используется.</small>}<button className="primary analyze" disabled={loading||(!text.trim()&&!file)}>{loading?<><span className="spinner"/> Разбираем задание…</>:'Разобрать задание →'}</button>{loading&&<p className="muted" role="status">Выделяем главное и собираем шаги. Обычно это занимает до 30 секунд.</p>}</fieldset></form></section>}
    {error&&<p className="error" role="alert">{error}</p>}
    {plan&&<><section className="card goal"><span className="eyebrow">ВОТ К ЧЕМУ ИДЁМ</span><h2>{plan.goal}</h2><div className="progress-label"><span>Твой прогресс</span><strong>{done} из {plan.steps.length} шагов</strong></div><progress value={done} max={plan.steps.length}/>{done===plan.steps.length&&<p>Всё готово. Отличная работа!</p>}</section><div className="columns"><div><section className="today card"><span className="eyebrow">{pretty(plan.today.date)}</span><h2>Фокус на сегодня</h2>{!plan.deadline_date?<p>Укажите дату сдачи, чтобы увидеть план на сегодня.</p>:plan.today.steps.length?<ul>{plan.today.steps.map(s=><li key={s.id} className={s.done?'done':''}>{s.done?'✓ ':''}{s.title}</li>)}</ul>:<p>На сегодня шагов нет. Можно посмотреть следующие в чек-листе.</p>}</section><section className="card"><h2>Что важно учесть</h2><h3>Требования</h3>{plan.requirements.length?<ul>{plan.requirements.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p className="muted">Не указаны в условии</p>}<h3>Ограничения</h3>{plan.constraints.length?<ul>{plan.constraints.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p className="muted">Не указаны в условии</p>}</section></div><section className="card checklist"><div className="card-heading"><h2>Твой чек-лист</h2><span className="muted">{plan.steps.length} шагов</span></div>{plan.steps.map((s,i)=><label className={'step '+(s.done?'done':'')} key={s.id}><input type="checkbox" checked={s.done} disabled={pending!==null||loading||saving} onChange={()=>toggle(s)}/><span><small>ШАГ {String(i+1).padStart(2,'0')}{s.due_date?' · '+pretty(s.due_date):''}</small><span>{s.title}</span>{s.due_date<plan.today.date&&!s.done&&<small className="overdue">Срок прошёл — вернись к этому шагу</small>}</span></label>)}<form className="deadline-form" onSubmit={schedule}><label htmlFor="plan-date">Успеть к дедлайну</label><div><input id="plan-date" type="date" required min={localDate()} value={due} onChange={e=>setDue(e.target.value)} disabled={saving||loading}/><button className="primary" disabled={!due||saving||loading||pending!==null}>{saving?'Сохраняем…':'Построить план по дням'}</button></div><small>Изменение даты сохранит выполненные шаги.</small></form></section></div></>}
    {!plan&&<div className="features"><div><b>01 / Понять</b><p>Цель, требования и ограничения</p></div><div><b>02 / Начать</b><p>Конкретные шаги вместо пустого листа</p></div><div><b>03 / Успеть</b><p>План по дням до самой сдачи</p></div></div>}</>}
    <footer>Без регистрации · План хранится 14 дней<span>Исходный текст и PDF не сохраняются на сервере</span></footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
